apiVersion: apps/v1
kind: Deployment
metadata:
  name: gl-ui-deployment
  labels:
    app: gl-ui
spec:
  replicas: 2
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: gl-ui
  template:
    metadata:
      labels:
        app: gl-ui
    spec:
      containers:
      - name: gl-ui
        image: zmad5306/gl-ui:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 128Mi
          limits:
            memory: 256Mi