apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gl-ingress
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
spec:
  backend:
    serviceName: gl-ui-service
    servicePort: 80
  rules:
  - host: grocery-list
    http:
      paths:
      - path: /api
        backend:
          serviceName: gl-api-service
          servicePort: 8080
      