apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gl-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: gl-ui-service
    servicePort: 80
  rules:
  - host: api.minikube
    http:
      paths:
      - path: /api
        backend:
          serviceName: gl-api-service
          servicePort: 8080

          