apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gl-ingress
spec:
  rules:
  - host: grocery-list
    http:
      paths:
      - path: /
        backend:
          serviceName: gl-ui-service
          servicePort: 80
      - path: /api
        backend:
          serviceName: gl-api-service
          servicePort: 8080
      