apiVersion: apps/v1
kind: Deployment
metadata:
  name: gl-api-deployment
  labels:
    app: gl-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: gl-api
  template:
    metadata:
      labels:
        app: gl-api
    spec:
      containers:
      - name: gl-api
        image: zmad5306/gl-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /api/actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 30
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /api/actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 30
          successThreshold: 1
          failureThreshold: 5
        resources:
          requests:
            memory: 128Mi
          limits:
            memory: 256Mi