apiVersion: apps/v1
kind: Deployment
metadata:
  name: gl-api-deployment
  labels:
    app: gl-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: gl-api
  template:
    metadata:
      labels:
        app: gl-api
    spec:
      containers:
      - name: gl-api
        image: zmad5306/gl-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /api/actuator/health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 30
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /api/actuator/health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 30
          successThreshold: 1
          failureThreshold: 3
