apiVersion: apps/v1
kind: Deployment
metadata:
  name: gl-list-deployment
  labels:
    app: gl-list
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: gl-list
  template:
    metadata:
      labels:
        app: gl-list
    spec:
      containers:
      - name: gl-list
        image: zmad5306/gl-list:latest
        imagePullPolicy: Always
        env:
          - name: mongo-db-uri
            valueFrom:
                configMapKeyRef:
                  name: gl-config
                  key: list-mongouri
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /list/actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 30
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /list/actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 30
          successThreshold: 1
          failureThreshold: 5
        resources:
          requests:
            memory: 128Mi
          limits:
            memory: 256Mi