apiVersion: apps/v1
kind: Deployment
metadata:
  name: gl-list-deployment
  labels:
    app: gl-list
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: gl-list
  template:
    metadata:
      labels:
        app: gl-list
    spec:
      containers:
      - name: gl-list
        image: zmad5306/gl-list:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 30
          successThreshold: 1
          failureThreshold: 3