apiVersion: apps/v1
kind: Deployment
metadata:
  name: gl-list-deployment
  labels:
    app: gl-list
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: gl-list
  template:
    metadata:
      labels:
        app: gl-list
    spec:
      containers:
      - name: gl-list
        image: zmad5306/gl-list:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /list/actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 10
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /list/actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 10